version: '3.8'
services:
  db:
    container_name: mysql
    image: mysql:8.0.29
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local